// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Mhbn5Jq8nPX-2hiqgLgLYfW21HxrvrA',
    appId: '1:364357716269:web:83f0a9de3dc1ffd16d2ba4',
    messagingSenderId: '364357716269',
    projectId: 'keyvalue-app',
    authDomain: 'keyvalue-app.firebaseapp.com',
    storageBucket: 'keyvalue-app.firebasestorage.app',
    measurementId: 'G-F7TD0LH08C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-u2IJ-FRWfcT2UaCz9EwBL2JeMR2ak9I',
    appId: '1:364357716269:android:0b38e59a56a3d76f6d2ba4',
    messagingSenderId: '364357716269',
    projectId: 'keyvalue-app',
    storageBucket: 'keyvalue-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdXCxeHvDBJCD3wvsZcOued9u78MlK5A',
    appId: '1:364357716269:ios:671b960fac7a2e096d2ba4',
    messagingSenderId: '364357716269',
    projectId: 'keyvalue-app',
    storageBucket: 'keyvalue-app.firebasestorage.app',
    iosBundleId: 'com.hejitech.widgetCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdXCxeHvDBJCD3wvsZcOued9u78MlK5A',
    appId: '1:364357716269:ios:671b960fac7a2e096d2ba4',
    messagingSenderId: '364357716269',
    projectId: 'keyvalue-app',
    storageBucket: 'keyvalue-app.firebasestorage.app',
    iosBundleId: 'com.hejitech.widgetCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Mhbn5Jq8nPX-2hiqgLgLYfW21HxrvrA',
    appId: '1:364357716269:web:2c8aefa9e98d69826d2ba4',
    messagingSenderId: '364357716269',
    projectId: 'keyvalue-app',
    authDomain: 'keyvalue-app.firebaseapp.com',
    storageBucket: 'keyvalue-app.firebasestorage.app',
    measurementId: 'G-TT75DXFHPF',
  );
}
