import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:keyvalue_app/l10n/app_localizations.dart' as app_l10n;
import 'package:keyvalue_app/theme.dart' as app_theme;
import 'package:keyvalue_dash/theme.dart' as dash_theme;
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

// This file will be generated by widgetbook_generator
import 'main.directories.g.dart';

void main() {
  runApp(const WidgetbookApp());
}

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(
              name: 'App Light',
              data: app_theme.AppTheme.lightTheme,
            ),
            WidgetbookTheme(
              name: 'Dash Light',
              data: dash_theme.AppTheme.lightTheme,
            ),
          ],
        ),
        LocalizationAddon(
          locales: [
            const Locale('en'),
            const Locale('zh'),
          ],
          localizationsDelegates: [
            app_l10n.AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
        ),
        DeviceFrameAddon(
          devices: [
            Devices.ios.iPhone13,
            Devices.android.samsungGalaxyS20,
            Devices.windows.wideMonitor,
          ],
        ),
        AlignmentAddon(),
      ],
    );
  }
}
